name: cppcheck-action

on: [push]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cppcheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          std:  c++20
          exclude_check: ./include/
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: publish report    
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cppcheck-report
          path: cppcheck_report.txt
