name: cppcheck-action

on: [pull_request]


permissions:
  pull-requests: write
  contents: read

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck


      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c++23 --force --inline-suppr \
            --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=checkersReport \
            --quiet --check-level=exhaustive ./src/ 2> cppcheck_report.txt
          if [ ! -s cppcheck_report.txt ]; then
            echo "✅ No error reported" > cppcheck_report.txt
          fi
          cat cppcheck_report.txt


      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: cppcheck_report.txt

      - name: publish report    
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cppcheck-report
          path: cppcheck_report.txt
